updating for nexus deployable

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -48,9 +48,26 @@ manage_incremental_build
 
 #switch here to curl a war file into the build, revert to normal maven build otherwise...
 
-if [ x"$ARTIFACT_URL" != "x" ]; then
-    echo "grabbing the artifact $ARTIFACT_URL"
-    curl -o ${DEPLOY_DIR}/ROOT.war -O ${ARTIFACT_URL}
+if [ x"NEXUS_URL" != "x" ]; then
+    echo "grabbing the artifact from the defined $NEXUS_URL"
+    #curl -o ${DEPLOY_DIR}/ROOT.war -O ${ARTIFACT_URL}
+
+    DEPLOYABLE_NAME="${ARTIFACT_ID}-${ARTIFACT_VERSION}.${EXTENSION}"
+    DEPLOYABLE_FULL_PATH="${NEXUS_URL}/service/local/artifact/maven/redirect?r=${REPOSITORY_NAME}&g=${GROUP_ID}&a=${ARTIFACT_ID}&c=${CLASSIFIER}&e=${EXTENSION}&v=${ARTIFACT_VERSION}"
+
+    #http://nexus-ci.cloudapps-a2ff.oslab.opentlc.com/service/local/artifact/maven/redirect?r=releases&g=org.openshift.quickstarts&a=tomcat-jdbc&c=&e=war&v=1.0.10"
+    #${NEXUS_URL}/service/local/artifact/maven/redirect?r=${REPOSITORY_NAME}&g=${GROUP_ID}&a=${ARTIFACT_ID}&c=${CLASSIFIER}&e=${EXTENSION}&v=${ARTIFACT_VERSION}"
+
+    echo "Started CURL Download from $DEPLOYABLE_FULL_PATH"
+    curl -L  "DEPLOYABLE_FULL_PATH" -o ${DEPLOY_DIR}/ROOT.war
+
+    if [ 0 -eq $? ]; then
+      echo "Download complete"
+    else
+      echo "Failed to Download Release Deployable"
+      exit 1
+    fi;
+
 else
     # If a pom.xml is present, this is a normal build scenario
     # so run maven.
